---
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@e3d2460bbb42d7710191569f88069044cfb9d8cf # v4.2.2

      - name: Run actionlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run:  |
          set -x
          pnpm install

      - name: Run Vitest
        run: pnpm vitest --run --no-color --coverage.enabled true

      - name: 'Report Coverage'
        uses:  davelosert/vitest-coverage-report-action@adec81c7327940e0578d70d0bbdd87b0ca21df55 # v2.8.2
        if: always()
